### ISSUE TITLE
[Feature] Implement support for Fan mode

### ISSUE THREAD

**Issue by TimofeyK** [yenoiwesa/homebridge-daikin-airbase#2]
Hey Matthieu! Thank you for such great quality plugin. It's superior to my [Cmd4/bash integration](https://github.com/TimofeyK/cmd4-Daikin-Airbase) so I am switching to your work :-)

There are a couple of options missing so far and Fan mode support is one of them

With HomeKit not supporting Fan mode directly the only solution I found is to create a separate Fan accessory

When Fan accessory is turned On the HeaterCooler changes to Off state and vice versa

I used this approach in my script and it worked well with the only issue that when you turn devices On in Home app the other one will not refresh and shown as On until HomeKit will query it again. With a single proper plugin this should work better

Fan service supports RotationSpeed characteristic so I think the code for that can be reused

It would be great if you add this

**Comment by yenoiwesa** [comment]
Hey @TimofeyK 👋 

Thanks for raising the feature request.

So I initially tried to have the fan service map the fan mode but that wasn't working great, because then the fan speed for the heater/cooler could no longer be controlled (the Home app won't show the fan speed slider if another service implements the fan speed characteristic for the same accessory).

So eventually my final solution is to have 4 services showing as grouped accessories in the Home app, with:
-   A heater/cooler service allowing to set the aircon to cool/heat or auto mode, as well as the threshold temperatures,
-   A switch allowing to turn on/off fan mode,
-   A fan service allowing to change the aircon's fan speed (low/medium/high) if the device supports changing fan speed,
-   A second switch allowing to turn on/off dry mode if the device supports that mode.

I have done some testing and everything seemed to work fine (I had to do some major refactoring of the code but that was expected).

I will publish a new version with that new feature tonight on `npm` (I'll update this ticket when done).

Then it would be great if you could give me your feedback about that new version!

**Comment by TimofeyK** [comment]
Wow! I thought you probably haven’t even see the request and turned out you already redesigned the whole plugin! :)

I will try it as soon it’s available via npm

**Comment by yenoiwesa** [comment]
Alright, @TimofeyK I just released version `1.2.0` of the plugin including these changes.
Have a try and let me know if that works as you expect.
👍

**Comment by TimofeyK** [comment]
Hey @yenoiwesa This works beautifully! I installed last night and played with modes for a while. Can't break it so far :-)

A separate Fan Speed accessory was a bit confusing at first but then I realised that its On/Off action is essentially the same as physical On/Off button on the aircon controller - it turns on last used mode. I like this solution, very logical!

I'd probably name Heater/Cooler accessory "Heat / Cool" or "Heat & Cool" because Home app shows long name as "Heating &..." on Favourite accessories page (one line is used for room name so accessory name can't wrap to the next line)

**Comment by TimofeyK** [comment]
@yenoiwesa 
I saw this twice but can’t replicate it at will

- Cooling mode is on
- All devices show separately in one room
- Tap Fan switch to turn it on
- It looks like Aircon control turns off, then immediately off and Fan control also turns off

Exactly the same happened when turning Dry mode while Cooling was on

**Comment by yenoiwesa** [comment]
@TimofeyK I had this issue a few times and then I was completely unable to reproduce it again somehow, after restarting the homebridge server.

I think it is caused by a race condition. The problem with dealing with multiple accessories, and in particular the Heater/Cooler one, is that Siri sends request to set the state of these accessories when opening the detailed view. I try to do my best to catch all these requests and accumulate them to send just one cohesive state change to the daikin airbase, but (and this is my best guess) I assume sometimes it escapes the time limit of the debouncing?

If you manage to find a pattern that reproduces this issue consistently, please do let me know.
I never had the issue when operating the aircon through Siri though, so for me it's not really a deal breaker.

As per the names, are you able to edit them directly from the Home app? (maybe after ungrouping them?) Each service supports the `Name` characteristic.
If not, I might change the names as you suggest.

**Comment by TimofeyK** [comment]
I only seen this twice and both times I switched between Cool, Fan and Dry several times within few minutes but no any certain pattern

I can rename of cause. What I meant is the default name. Not a big deal anyway

**Comment by yenoiwesa** [comment]
@TimofeyK I published a new patch release that includes the name change as you suggested.

Regarding the bug, I think I found the cause of the issue:
Sometimes (I don't know when or why exactly), when the state of the Heater/Cooler changes without a user interaction on that service  (say when it is turned off because you enabled Fan mode), the Home app will send a request to the accessory to set that state again (the state it is already in). But since the state is off it sends a request to turn off heater cooler. I was catering for that case by making sure to only send that request if it is in heat or cool mode, but due to a timing issue, the airbase still has the previous value (the airbase takes some time to refresh its values after a set).

So I will have to change my promise caching mechanism to be able to force a cached value I guess, with the value I set previously. I'll be working on that!

**Comment by TimofeyK** [comment]
I installed the update and so far it’s working perfectly. Wasn’t able to break it

Noticed a tiny UI inconsistency which I wouldn’t bother fixing. Writing it up just in case you’ll be bored one day :)

Changing Fan speed slider to 0% turns off the aircon. When you turn it on again the speed is still shown as 0% until values are re-read from the airbase controller

- In Home app turn on any mode
- Change Fan speed down one step e.g. to 50% using the slider
- Change the speed down to 0 using the slider - aircon turns off
- Without switching to other apps to avoid refresh turn on any mode - Fan speed turns on with 0% speed

**Comment by yenoiwesa** [comment]
@TimofeyK I just released `v1.2.3` which contains the bug fix for the Dry/Fan mode turning off when turning it on for cool mode (phew..).

Now, I just tested your second bug you described above and... I can definitely reproduce. Homekit is killing me lol, it turns out that mapping multiple accessories to just one physical one is not that easy.
I'll have a look at it when I have a chance, but since it is purely cosmetic (unlike the Dry/Fan mode one) I might decide to leave it as is.

Thanks again for your help!

**Comment by yenoiwesa** [comment]
@TimofeyK I finally found the cause of the issue with the inconsistent fan speed rotation. Homekit is picky and refuses to have a fan inactive with a fan rotation speed other than 0. Everything works fine when that happens **but** the display in the Home app 🤷‍♂ 

I fixed the issue in release `1.2.4`. Try it out and let me know.
Hopefully everything is good and I can close this issue :-)

**Comment by TimofeyK** [comment]
What can I say @yenoiwesa 
I think it’s too perfect. Let’s close the issue before we break something :)

**Comment by yenoiwesa** [comment]
@TimofeyK nice! I'll close it quickly then!!! hehe
